# NumPy

Extensión de Python para trabajar con vectores y matrices

## Instalación en Jupyter

* Con anaconda:
```bash
conda install numpy
```
* Sin anaconda
```bash
pip install numpy
```

## Arrays 

In [14]:
import numpy as np # a partir de ahora utilizaremos np (seudonimo) en vez de numpy 

In [28]:
print("array unidimensional:")
array_unidimensional = np.array([1,2,3,4])
print(array_unidimensional)
print("array bidimensional:")
array_bidimensional = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_bidimensional)
print("una fila:")
print(array_bidimensional[0])
print("un elemento de la fila 1 y clumna 1:")
print(array_bidimensional[0][0])
print("columna 0")
print(array_bidimensional[:,0])
print("columna 0 y 1")
print(array_bidimensional[:,:2])

array unidimensional:
[1 2 3 4]
array bidimensional:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
una fila:
[1 2 3]
un elemento de la fila 1 y clumna 1:
1
columna 0
[1 4 7]
columna 0 y 1
[[1 2]
 [4 5]
 [7 8]]


In [ ]:
lista = [1,2,3,4,5,6]

In [3]:
# convertimos la lista en un array
array = np.array(lista)
print(array)

In [7]:
 # Creamos una lista doble, es decir, una lista de 3 elementos que contiene a su vez 3 listas
lista_array = [[1,2,3],[4,5,6],[7,8,9]]
# lo convertimos en un array de 2 dimensiones (matriz)
array_bidimensional = np.array(lista_array)
print(array_bidimensional)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Funciones: arange, zeros, ones, linspace, eye, reshape

In [34]:
import numpy as np

# arange
array_1= np.arange(1,11)  # arrange tiene los parámetros (comienzo, final-1, paso)
array_2= np.arange(1,11,2) # tercer parámetro es el step (paso), generando en este caso un array de 2 en 2
print("Ejemplo de arrange:")
print(array_1)
print(array_2)

# zeros
array_zeros = np.zeros((3,4)) # crea una matriz de ceros de 3x4 
print("Ejemplo de zeros:")
print(array_zeros)

# unos
array_unos = np.ones((3,4))
print("Ejemplo de unos:")
print(array_unos)

# linspace
array_line = np.linspace(1,10,20) # crea un vector de 20 elementos con los valores del 1 al 10 (interpola)
print("Ejemplo de linspace:")
print(array_line)

# eye 
array_eye = np.eye(5) # crea una matriz cuadrada de 'n' filas y columnas 
print("Ejemplo de matriz unitaria:")
print(array_eye)

# reshape
# Si queremos convertir un vector de 9 elementos en matriz de 3 dimensiones
vector = np.arange(1,10)
print("Ejemplo de vector convertido en matriz 3x3:")
matriz = vector.reshape(3,3) # con esto podemos cambiar el formato de las matrices en número de filas y número de columnas
print(matriz)

Ejemplo de arrange:
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
Ejemplo de zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ejemplo de unos:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ejemplo de linspace:
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
Ejemplo de matriz unitaria:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Ejemplo de vector convertido en matriz 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Números aleatorios: rand , randn, randint 

In [40]:
import numpy as np

# Imprimir 5 numeros aleatorios del 0 al 1. Es una distribución uniforme de números positivos.
print("\n- vector de 5 números aleatorios con distribución uniforme:")
print(np.random.rand(5))
print("\n- array de 2x3 elementos:")
print(np.random.rand(2,3))

# Distribución normal con valores tanto positivos como negativos
print("\n- vector de 5 números aleatorios con distribución normal:")
print(np.random.randn(5))
print("\n- array de 2x3 elementos aleatorios con distribución normal:")
print(np.random.randn(2,3))

# Numeros aleatorios enteros
print("\n- número aleatorio entero entre 1 y 10:")
print(np.random.randint(1,11))
print("\n- 5 números aleatorios enteros entre 1 y 10:")
print(np.random.randint(1,11,5))




- vector de 5 números aleatorios con distribución uniforme:
[0.86710528 0.12624962 0.05296099 0.80954369 0.74344356]

- array de 2x3 elementos:
[[0.18310122 0.7745543  0.24964119]
 [0.26729985 0.71147264 0.65160231]]

- vector de 5 números aleatorios con distribución normal:
[0.33683045 0.25501614 0.08789847 0.55257108 0.89609282]

- array de 2x3 elementos aleatorios con distribución normal:
[[-0.29494491 -2.26176759  0.3063986 ]
 [-0.55793458  1.73302787 -0.29226914]]

- número aleatorio entero entre 1 y 10:
2

- 5 números aleatorios enteros entre 1 y 10:
[3 3 5 8 9]


## Números máximos y mínimos 

In [10]:
# obtenemos un array de numeros aleatorios
import numpy as np
array_random = np.random.randint(-100,100,50)
max_value = array_random.max()
min_value = array_random.min()
max_position = array_random.argmax() + 1
min_position = array_random.argmin() + 1
print(array_random)
print("\n valor maximo: ",max_value," en posicion (",max_position,") y valor minimo:",min_value,"en posicion(",min_position,")")


[-15 -34  16 -54 -80  98  46  90 -75   1 -74 -78  82 -46  26  27 -39 -35
  70   1   6 -78  72  82  33  71   4 -53 -66  15  81  70 -66 -38  47 -79
  61 -19  75   2 -93 -12  82  64  86  51 -24   2 -72  38]

 valor maximo:  98  en posicion ( 6 ) y valor minimo: -93 en posicion( 41 )


## Obtener partes de un array y de una matriz

In [17]:
import numpy as np

# Creamos un vector
array = np.arange(1,10)

# Como obtener diferentes partes de un array
print(array)
print(array[3:6])
print(array[3:])
print(array[:3])

# Copiar un array
array_cp = array.copy()
print(array_cp)

# transformamos el array unidimensional en bidimensional (matriz)
matriz = array.reshape(3,3)
print("Matriz resultante:")
print(matriz)
print("Dos primeras filas:")
print(matriz[:2])
print("Dos últimas filas:")
print(matriz[1:])
print("Columna 2:")
print(matriz[:,1])
print("Dos últimas columnas:")
print(matriz[:,1:])
print("Ultima columna:")
print(matriz[:,-1])

[1 2 3 4 5 6 7 8 9]
[4 5 6]
[4 5 6 7 8 9]
[1 2 3]
[1 2 3 4 5 6 7 8 9]
Matriz resultante:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dos primeras filas:
[[1 2 3]
 [4 5 6]]
Dos últimas filas:
[[4 5 6]
 [7 8 9]]
Columna 2:
[2 5 8]
Dos últimas columnas:
[[2 3]
 [5 6]
 [8 9]]
Ultima columna:
[3 6 9]


## Operaciones con arrays 

In [34]:
array1 = np.array([0,1,2])
array2 = np.array([3,4,5])

In [37]:
print(array1 + 10)
print(array1 - array1)
print(array1 * 10)
print(array1 + array2)
print(array1 * array2)

[10 11 12]
[0 0 0]
[ 0 10 20]
[3 5 7]
[ 0  4 10]


## Ejercicio 1: 

In [24]:
import numpy as np

# valor minimo de 10 y maximo de 39
array = np.arange(10,40)
matriz = array.reshape(3,10)
print(matriz)
print("\nElemento de la esquina superior derecha de la matriz:")
print(matriz[0,-1])

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

Elemento de la esquina superior derecha de la matriz:
19


## Ejercicio 2: 

In [29]:
import numpy as mp

# array de 9 valores aleatorios de 0 a 100
array = np.random.randint(0,100,9)
matriz = array.reshape(3,3)
print(matriz)
print("\nElemento de la esquina inferior derecha:")
print(matriz[-1,-1])

[[ 3 84  2]
 [33 29 43]
 [36 16 92]]

Elemento de la esquina inferior derecha:
92
