# Random Forest Tutorial: Bosques aleatorios

Random forest es una combinación de árboles de decisión, donde cada árbol selecciona una clase y luego se combinan decisiones de cada árbol, para seleccionar una clase final ganadora.
Es uno de los algoritmos de aprendizaje de clasificación con **mayor precisión**.
Funciona eficientemente en bases de datos grandes.
Puede manejar cientos de variables de entrada.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/home/ikari/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/ikari/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/ikari/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/ikari/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/ikari/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate 

In [4]:
vinos = pd.read_csv('./datasets/vinos/original.csv')

In [5]:
vinos

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280/OD315 of diluted wines  Proline Wine Type  
0                            3.92   1065.0       One  
1                            3.40   1050.0       One  
2                            3.17   1185.0       One  
3                            3.45   1480.0       One  
4                            2.93    735.0       One  
..                            ...      ...       ...  
173                          1.74    740.0     Three  
174                          1.56    750.0     Three  
175                          1.56    835.0     Three  
176                          1.62    840.0     Three  
177                          1.60    560.0     Three  

[178 rows x 14 columns]

In [6]:
# separamos entre características y columna objetivo
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']

In [7]:
# separamos los datos de test y entrenamiento
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

In [8]:
# entrenamos el modelo
from sklearn.ensemble import RandomForestClassifier
randomforest = RandomForestClassifier(n_estimators=80) # le pasamos el numero de estimadores (arboles uqe va a hacer para estimar el resultado)
randomforest.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=80,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [9]:
predicciones = randomforest.predict(X_test)

In [10]:
# si lo comparamos nos fijamos que lo ha predecido todo
dicc = {'Wine Type Test': y_test, 'Wine Type Predictes': predicciones}
pd.DataFrame(dicc)

Wine Type Test Wine Type Predictes
158          Three               Three
48             One                 One
22             One                 One
37             One                 One
81             Two                 Two
65             Two                 Two
176          Three               Three
74             Two                 Two
114            Two                 Two
67             Two                 Two
121            Two                 Two
79             Two                 Two
171          Three               Three
128            Two                 Two
139          Three               Three
90             Two                 Two
150          Three               Three
93             Two                 Two
27             One                 One
91             Two                 Two
163          Three               Three
116            Two                 Two
144          Three               Three
12             One                 One
161          Three               Three
28             One                 One
92             Two                 Two
102            Two                 Two
177          Three               Three
49             One                 One
105            Two                 Two
115            Two                 Two
69             Two                 Two
136          Three               Three
109            Two                 Two
41             One                 One
80             Two                 Two
123            Two                 Two
55             One                 One
68             Two                 Two
89             Two                 Two
44             One                 One
36             One                 One
72             Two                 Two
53             One                 One
86             Two                 Two
70             Two                 Two
17             One                 One
50             One                 One
56             One                 One
138          Three               Three
78             Two                 Two
160          Three               Three
3              One                 One

In [11]:
# la precisión es máxima en todos los vinos
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      1.00      1.00        16
       Three       1.00      1.00      1.00        12
         Two       1.00      1.00      1.00        26

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [12]:
# matriz de confusión
print(confusion_matrix(y_test, predicciones))

[[16  0  0]
 [ 0 12  0]
 [ 0  0 26]]
